import type { Lang } from '../i18n/utils';
import type {
  ChannelFeature,
  ChannelStep,
  ChannelUseCase,
  ChannelTrustItem,
} from '../components/ChannelPageLayout.astro';

export type ChannelId = 'whatsapp' | 'instagram' | 'facebook' | 'tiktok';

export interface ChannelPageData {
  lang: Lang;
  title: string;
  description: string;
  canonical: string;
  ogImage: string;
  badge: string;
  heroTitle: string;
  heroAccent: string;
  heroLead: string;
  source: string;
  heroHint: string;
  channelId: ChannelId;
  stats: { v: string; l: string }[];
  featuresEyebrow: string;
  featuresTitle: string;
  featuresTitleAccent: string;
  features: ChannelFeature[];
  stepsEyebrow: string;
  stepsTitle: string;
  stepsTitleAccent: string;
  steps: ChannelStep[];
  useCasesEyebrow: string;
  useCasesTitle: string;
  useCasesTitleAccent: string;
  useCases: ChannelUseCase[];
  trustEyebrow: string;
  trustTitle: string;
  trustTitleAccent: string;
  trustLead: string;
  trustBullets: string[];
  trustItems: ChannelTrustItem[];
  ctaTitle: string;
  ctaAccent: string;
  ctaLead: string;
  ctaSource: string;
  ctaHint: string;
}

const pages: Record<Lang, Record<ChannelId, ChannelPageData>> = {
  es: {
    whatsapp: {
      lang: 'es',
      title: 'Shadia AI para WhatsApp — Tu operación en el canal favorito de tus clientes',
      description: 'Automatiza citas, respuestas y ventas en WhatsApp. Agentes IA 24/7 en el canal donde ya están tus clientes.',
      canonical: 'https://shadia.ai/es/canales/whatsapp',
      ogImage: '/og/whatsapp-es.png',
      badge: 'WhatsApp · Canal oficial',
      heroTitle: 'Tu operación',
      heroAccent: 'donde ya están tus clientes.',
      heroLead: 'Shadia gestiona respuestas, citas y seguimiento en WhatsApp. Tu equipo interviene solo cuando aporta valor real.',
      source: 'channel_whatsapp_hero',
      heroHint: 'API oficial de WhatsApp · Sin tarjeta de crédito',
      channelId: 'whatsapp',
      stats: [
        { v: '98%', l: 'Tasa de apertura de mensajes' },
        { v: '2B+', l: 'Usuarios activos en WhatsApp' },
        { v: '< 90s', l: 'Tiempo promedio de respuesta' },
        { v: '24/7', l: 'Disponibilidad del agente' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'Todo lo que necesitas,',
      featuresTitleAccent: 'directamente en WhatsApp.',
      features: [
        { icon: 'zap', title: 'Respuestas en segundos', desc: 'Shadia responde al instante, 24/7. Sin tiempos de espera ni clientes perdidos.' },
        { icon: 'bot', title: 'Agente que conoce tu negocio', desc: 'Describe tu operación en lenguaje natural. La IA gestiona preguntas, citas y ventas.' },
        { icon: 'calendar', title: 'Citas por WhatsApp', desc: 'Agenda, confirma y reconfirma citas en el chat. Calendario siempre sincronizado.' },
        { icon: 'megaphone', title: 'Mensajes masivos', desc: 'Campañas a segmentos con plantillas aprobadas. Hasta 98% de apertura.' },
        { icon: 'tag', title: 'Contactos y etiquetas', desc: 'Organiza cada conversación con tags, atributos y notas del equipo.' },
        { icon: 'users', title: 'Equipo colaborativo', desc: 'Asigna conversaciones y colabora en un solo lugar.' },
        { icon: 'link', title: 'API oficial', desc: 'WhatsApp Business API. Número protegido y plantillas premium.' },
        { icon: 'paperclip', title: 'Archivos y adjuntos', desc: 'Documentos, imágenes y audios organizados por contacto.' },
        { icon: 'bar-chart', title: 'Visibilidad total', desc: 'Métricas de conversaciones y rendimiento en tiempo real.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'De cero a operando',
      stepsTitleAccent: 'en menos de una hora.',
      steps: [
        { n: '01', title: 'Conecta tu número', desc: 'Vincula WhatsApp Business en minutos, sin configuraciones técnicas.' },
        { n: '02', title: 'Describe tu operación', desc: 'Cuéntale a Shadia cómo atiendes. Sin código.' },
        { n: '03', title: 'Shadia empieza', desc: 'Responde, agenda y escala desde el primer mensaje.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Funciona para',
      useCasesTitleAccent: 'cualquier negocio.',
      useCases: [
        { icon: 'heart', title: 'Clínicas y salud', desc: 'Citas, recordatorios y dudas frecuentes por WhatsApp.' },
        { icon: 'scissors', title: 'Salones y spa', desc: 'Llena la agenda sin llamadas. Menos no-shows.' },
        { icon: 'graduation-cap', title: 'Educación', desc: 'Prospectos, inscripciones y recordatorios de clases.' },
        { icon: 'trending-up', title: 'Ventas', desc: 'Califica leads, envía catálogos y cierra en el chat.' },
      ],
      trustEyebrow: 'API Oficial',
      trustTitle: 'Conectado a la',
      trustTitleAccent: 'WhatsApp Business API oficial.',
      trustLead: 'Shadia opera sobre la API oficial de Meta. Tu número está protegido con plantillas, catálogos y botones interactivos.',
      trustBullets: [
        'Número verificado con sello verde',
        'Plantillas de mensajes aprobadas',
        'Catálogos de productos integrados',
        'Botones interactivos y listas',
      ],
      trustItems: [
        { label: 'Meta Business Partner', badge: 'Verificado' },
        { label: 'WhatsApp Business API', badge: 'Oficial' },
        { label: 'Datos cifrados E2E', badge: 'Seguro' },
        { label: 'Uptime garantizado', badge: '99.9%' },
      ],
      ctaTitle: 'Tu negocio en WhatsApp,',
      ctaAccent: 'sin interrupciones.',
      ctaLead: 'Conecta tu número hoy y Shadia empieza a gestionar tus conversaciones desde el primer minuto.',
      ctaSource: 'channel_whatsapp_cta',
      ctaHint: 'Sin tarjeta de crédito · API oficial · Listo en menos de 1 hora',
    },
    instagram: {
      lang: 'es',
      title: 'Shadia AI para Instagram — Convierte DMs en clientes',
      description: 'Automatiza DMs y comentarios de Instagram. IA que responde, califica y agenda citas 24/7.',
      canonical: 'https://shadia.ai/es/canales/instagram',
      ogImage: '/og/instagram-es.png',
      badge: 'Instagram · DMs y comentarios',
      heroTitle: 'Cada DM,',
      heroAccent: 'una oportunidad atendida.',
      heroLead: 'Shadia gestiona DMs y comentarios — respondiendo al instante, calificando leads y agendando citas las 24 horas.',
      source: 'channel_instagram_hero',
      heroHint: 'Conversaciones unificadas · Sin tarjeta de crédito',
      channelId: 'instagram',
      stats: [
        { v: '2B+', l: 'Usuarios activos en Instagram' },
        { v: '< 2 min', l: 'Primera respuesta con IA' },
        { v: '24/7', l: 'DMs atendidos fuera de horario' },
        { v: 'All channels', l: 'Instagram + WhatsApp juntos' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'Instagram como canal',
      featuresTitleAccent: 'de conversión real.',
      features: [
        { icon: 'message-square', title: 'DMs automatizados', desc: 'Preguntas, citas y ventas sin que tu equipo esté pendiente del celular.' },
        { icon: 'message-square', title: 'Respuesta a comentarios', desc: 'Detecta intención de compra y abre conversación privada automáticamente.' },
        { icon: 'smartphone', title: 'Stories y menciones', desc: 'Convierte reacciones y menciones en oportunidades de negocio.' },
        { icon: 'shopping-bag', title: 'Ventas en Instagram', desc: 'Catálogos, calificación de leads y cierre en el chat.' },
        { icon: 'bar-chart', title: 'Métricas', desc: 'Qué conversaciones convierten y qué respuestas funcionan.' },
        { icon: 'users', title: 'Espacio de equipo', desc: 'Instagram junto con WhatsApp y más en un solo lugar.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'Conecta Instagram',
      stepsTitleAccent: 'y empieza en minutos.',
      steps: [
        { n: '01', title: 'Vincula tu cuenta', desc: 'Conexión oficial con permisos de mensajes.' },
        { n: '02', title: 'Define el tono', desc: 'Precios, servicios y reglas de escalación.' },
        { n: '03', title: 'La IA responde', desc: 'DMs y comentarios gestionados al instante.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Ideal para marcas',
      useCasesTitleAccent: 'que viven en Instagram.',
      useCases: [
        { icon: 'scissors', title: 'Belleza y estética', desc: 'Agenda desde el DM del post que viralizó.' },
        { icon: 'shopping-bag', title: 'Retail', desc: 'Responde preguntas de producto y stock al momento.' },
        { icon: 'heart', title: 'Bienestar', desc: 'Convierte seguidores en citas confirmadas.' },
        { icon: 'trending-up', title: 'Agencias', desc: 'Una plataforma para todas las cuentas de clientes.' },
      ],
      trustEyebrow: 'Integración oficial',
      trustTitle: 'API de Meta',
      trustTitleAccent: 'para Instagram Messaging.',
      trustLead: 'Conexión segura con permisos granulares. Tu cuenta protegida y auditable.',
      trustBullets: [
        'Permisos oficiales de mensajería',
        'Historial unificado con otros canales',
        'Escalación al equipo con contexto',
        'Cumplimiento de políticas de Meta',
      ],
      trustItems: [
        { label: 'Instagram Messaging API', badge: 'Oficial' },
        { label: 'Plataforma unificada', badge: 'Incluido' },
        { label: 'Handoff humano', badge: '1 clic' },
        { label: 'Disponibilidad', badge: '24/7' },
      ],
      ctaTitle: 'Tus DMs de Instagram,',
      ctaAccent: 'siempre atendidos.',
      ctaLead: 'Conecta Instagram y deja que Shadia convierta cada mensaje en cita o venta.',
      ctaSource: 'channel_instagram_cta',
      ctaHint: 'Sin tarjeta de crédito · Setup en minutos',
    },
    facebook: {
      lang: 'es',
      title: 'Shadia AI para Messenger — Facebook Messenger automatizado',
      description: 'Atiende Messenger y Facebook con IA. Unifica con WhatsApp e Instagram en una sola operación.',
      canonical: 'https://shadia.ai/es/canales/facebook',
      ogImage: '/og/facebook-es.png',
      badge: 'Messenger · Facebook',
      heroTitle: 'Messenger atendido',
      heroAccent: 'sin perder el hilo.',
      heroLead: 'Shadia responde en Messenger, califica consultas y puede continuar la conversación en WhatsApp cuando convenga.',
      source: 'channel_facebook_hero',
      heroHint: 'Meta Business · Conversaciones unificadas',
      channelId: 'facebook',
      stats: [
        { v: '1.3B+', l: 'Usuarios de Messenger' },
        { v: '< 90s', l: 'Respuesta promedio' },
        { v: '24/7', l: 'Cobertura con IA' },
        { v: 'Multi', l: 'Handoff a WhatsApp' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'Messenger conectado',
      featuresTitleAccent: 'a tu operación.',
      features: [
        { icon: 'message-square', title: 'Respuestas instantáneas', desc: 'Nunca dejes un mensaje de tu página sin respuesta.' },
        { icon: 'bot', title: 'IA contextual', desc: 'Mismo conocimiento de negocio que en WhatsApp e Instagram.' },
        { icon: 'repeat', title: 'Continuar en WhatsApp', desc: 'Ofrece seguir por el canal preferido del cliente en RD y LATAM.' },
        { icon: 'users', title: 'Espacio del equipo', desc: 'Tu equipo ve Messenger junto al resto de canales.' },
        { icon: 'tag', title: 'Etiquetas y notas', desc: 'Contexto compartido en cada conversación.' },
        { icon: 'bar-chart', title: 'Reportes', desc: 'Volumen, tiempos y conversiones por canal.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'Conecta tu página',
      stepsTitleAccent: 'de Facebook.',
      steps: [
        { n: '01', title: 'Vincula la página', desc: 'Autoriza Messenger desde Meta Business.' },
        { n: '02', title: 'Configura reglas', desc: 'Horarios, precios y cuándo escalar.' },
        { n: '03', title: 'Operación activa', desc: 'La IA responde y tu equipo supervisa.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Para negocios con',
      useCasesTitleAccent: 'presencia en Facebook.',
      useCases: [
        { icon: 'store', title: 'Comercios locales', desc: 'Consultas de horario, precios y ubicación.' },
        { icon: 'heart', title: 'Servicios', desc: 'Agenda citas desde la página de Facebook.' },
        { icon: 'trending-up', title: 'Ventas', desc: 'Seguimiento automático de prospectos.' },
      ],
      trustEyebrow: 'Meta',
      trustTitle: 'Messenger',
      trustTitleAccent: 'Business API.',
      trustLead: 'Integración oficial con tu página de Facebook y permisos de mensajería.',
      trustBullets: [
        'Página verificada de negocio',
        'Mensajes dentro de políticas de Meta',
        'Historial en plataforma unificada',
        'Escalación al humano con contexto',
      ],
      trustItems: [
        { label: 'Messenger API', badge: 'Oficial' },
        { label: 'Meta Business Suite', badge: 'Compatible' },
        { label: 'Handoff WhatsApp', badge: 'Opcional' },
        { label: 'Uptime', badge: '99.9%' },
      ],
      ctaTitle: 'Tu página de Facebook,',
      ctaAccent: 'siempre respondiendo.',
      ctaLead: 'Conecta Messenger y unifica la atención con el resto de tus canales.',
      ctaSource: 'channel_facebook_cta',
      ctaHint: 'Sin tarjeta de crédito · Meta Business',
    },
    tiktok: {
      lang: 'es',
      title: 'Shadia AI para TikTok — DMs que convierten',
      description: 'Responde DMs de TikTok con IA. Convierte interés en citas y ventas reales.',
      canonical: 'https://shadia.ai/es/canales/tiktok',
      ogImage: '/og/tiktok-es.png',
      badge: 'TikTok · Mensajes directos',
      heroTitle: 'DMs de TikTok',
      heroAccent: 'que llegan a cita.',
      heroLead: 'Shadia atiende mensajes de TikTok al instante y lleva la conversación a una cita o venta — con el mismo contexto en tu plataforma.',
      source: 'channel_tiktok_hero',
      heroHint: 'Conversaciones unificadas · Sin tarjeta',
      channelId: 'tiktok',
      stats: [
        { v: '1B+', l: 'Usuarios activos en TikTok' },
        { v: '< 2 min', l: 'Primera respuesta' },
        { v: '24/7', l: 'DMs fuera de horario' },
        { v: '1 lugar', l: 'Todos los canales juntos' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'TikTok en tu',
      featuresTitleAccent: 'operación unificada.',
      features: [
        { icon: 'message-square', title: 'DMs con IA', desc: 'Responde preguntas y ofrece siguiente paso sin demora.' },
        { icon: 'zap', title: 'Velocidad', desc: 'Captura el interés del video antes de que se enfríe.' },
        { icon: 'calendar', title: 'Citas', desc: 'Agenda desde el DM como en WhatsApp.' },
        { icon: 'users', title: 'Equipo', desc: 'TikTok y otros canales en el mismo lugar.' },
        { icon: 'bot', title: 'Mismo agente', desc: 'Reglas y tono consistentes en todos los canales.' },
        { icon: 'bar-chart', title: 'Métricas', desc: 'Qué DMs convierten en clientes.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'Conecta TikTok',
      stepsTitleAccent: 'en pocos pasos.',
      steps: [
        { n: '01', title: 'Autoriza la cuenta', desc: 'Conexión segura para mensajes.' },
        { n: '02', title: 'Configura', desc: 'Servicios, precios y escalación.' },
        { n: '03', title: 'Empieza', desc: 'La IA responde desde el primer DM.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Para marcas',
      useCasesTitleAccent: 'que crecen en TikTok.',
      useCases: [
        { icon: 'scissors', title: 'Belleza', desc: 'Del video viral a la cita confirmada.' },
        { icon: 'shopping-bag', title: 'E-commerce', desc: 'Responde stock y envíos al instante.' },
        { icon: 'graduation-cap', title: 'Cursos', desc: 'Inscripciones desde DMs.' },
        { icon: 'trending-up', title: 'Creators', desc: 'Gestiona volumen sin perder leads.' },
      ],
      trustEyebrow: 'Plataforma',
      trustTitle: 'TikTok',
      trustTitleAccent: 'integrado con Shadia.',
      trustLead: 'Mensajes directos en la misma plataforma que WhatsApp, Instagram y Messenger.',
      trustBullets: [
        'DMs en plataforma unificada',
        'Contexto compartido por contacto',
        'IA con reglas de tu negocio',
        'Escalación al equipo',
      ],
      trustItems: [
        { label: 'TikTok Messaging', badge: 'Conectado' },
        { label: 'Plataforma unificada', badge: 'Incluido' },
        { label: 'IA 24/7', badge: 'Activo' },
        { label: 'Handoff', badge: 'Humano' },
      ],
      ctaTitle: 'Tus DMs de TikTok,',
      ctaAccent: 'convertidos en clientes.',
      ctaLead: 'Conecta TikTok y no pierdas el momentum de cada video.',
      ctaSource: 'channel_tiktok_cta',
      ctaHint: 'Sin tarjeta de crédito · Setup rápido',
    },
  },
  en: {
    whatsapp: {
      lang: 'en',
      title: 'Shadia AI for WhatsApp — Your operation in your customers\' favorite channel',
      description: 'Automate appointments, responses and sales on WhatsApp. AI agents 24/7 where your customers already are.',
      canonical: 'https://shadia.ai/en/channels/whatsapp',
      ogImage: '/og/whatsapp-en.png',
      badge: 'WhatsApp · Official channel',
      heroTitle: 'Your operation,',
      heroAccent: 'where customers already are.',
      heroLead: 'Shadia handles replies, scheduling and follow-ups on WhatsApp. Your team steps in only when it matters.',
      source: 'channel_whatsapp_hero',
      heroHint: 'Official WhatsApp API · No credit card',
      channelId: 'whatsapp',
      stats: [
        { v: '98%', l: 'Message open rate' },
        { v: '2B+', l: 'Active WhatsApp users' },
        { v: '< 90s', l: 'Average response time' },
        { v: '24/7', l: 'Agent availability' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'Everything you need,',
      featuresTitleAccent: 'right in WhatsApp.',
      features: [
        { icon: 'zap', title: 'Instant replies', desc: 'Shadia responds 24/7 so no lead waits on a reply.' },
        { icon: 'bot', title: 'Business-aware AI', desc: 'Describe how you operate. AI handles FAQs, booking and sales.' },
        { icon: 'calendar', title: 'Appointments in chat', desc: 'Book, confirm and reschedule without phone tag.' },
        { icon: 'megaphone', title: 'Broadcast campaigns', desc: 'Approved templates to segments that actually get read.' },
        { icon: 'tag', title: 'Contacts & tags', desc: 'Tags, attributes and internal notes on every thread.' },
        { icon: 'users', title: 'Team workspace', desc: 'Assign, mention and collaborate in one place.' },
        { icon: 'link', title: 'Official API', desc: 'WhatsApp Business API with protected numbers and templates.' },
        { icon: 'paperclip', title: 'Files & media', desc: 'Docs, images and voice notes organized per contact.' },
        { icon: 'bar-chart', title: 'Live metrics', desc: 'Response times and resolution rates in real time.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Live in under',
      stepsTitleAccent: 'an hour.',
      steps: [
        { n: '01', title: 'Connect your number', desc: 'Link WhatsApp Business in minutes.' },
        { n: '02', title: 'Describe your workflow', desc: 'Plain language — no code.' },
        { n: '03', title: 'Shadia goes live', desc: 'Replies, books and escalates from message one.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'Built for',
      useCasesTitleAccent: 'any customer-facing team.',
      useCases: [
        { icon: 'heart', title: 'Healthcare', desc: 'Scheduling, reminders and common patient questions.' },
        { icon: 'scissors', title: 'Salons & spas', desc: 'Fill the calendar without phone calls.' },
        { icon: 'graduation-cap', title: 'Education', desc: 'Prospects, enrollment and class reminders.' },
        { icon: 'trending-up', title: 'Sales', desc: 'Qualify leads and close in the thread.' },
      ],
      trustEyebrow: 'Official API',
      trustTitle: 'Connected to',
      trustTitleAccent: 'WhatsApp Business API.',
      trustLead: 'Shadia runs on Meta\'s official API — protected number, templates, catalogs and interactive buttons.',
      trustBullets: [
        'Verified business number',
        'Approved message templates',
        'Product catalogs',
        'Interactive buttons & lists',
      ],
      trustItems: [
        { label: 'Meta Business Partner', badge: 'Verified' },
        { label: 'WhatsApp Business API', badge: 'Official' },
        { label: 'End-to-end encryption', badge: 'Secure' },
        { label: 'Guaranteed uptime', badge: '99.9%' },
      ],
      ctaTitle: 'Your business on WhatsApp,',
      ctaAccent: 'without the backlog.',
      ctaLead: 'Connect your number today and Shadia starts managing conversations immediately.',
      ctaSource: 'channel_whatsapp_cta',
      ctaHint: 'No credit card · Official API · Under 1 hour setup',
    },
    instagram: {
      lang: 'en',
      title: 'Shadia AI for Instagram — Turn DMs into booked customers',
      description: 'Automate Instagram DMs and comments. AI that replies, qualifies and books 24/7.',
      canonical: 'https://shadia.ai/en/channels/instagram',
      ogImage: '/og/instagram-en.png',
      badge: 'Instagram · DMs & comments',
      heroTitle: 'Every DM,',
      heroAccent: 'handled like revenue.',
      heroLead: 'Shadia manages Instagram DMs and comments — instant replies, lead qualification and booking around the clock.',
      source: 'channel_instagram_hero',
      heroHint: 'Unified platform · No credit card',
      channelId: 'instagram',
      stats: [
        { v: '2B+', l: 'Monthly Instagram users' },
        { v: '< 2 min', l: 'First reply with AI' },
        { v: '24/7', l: 'After-hours DM coverage' },
        { v: 'All channels', l: 'Instagram + SMS together' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'Instagram as a',
      featuresTitleAccent: 'conversion channel.',
      features: [
        { icon: 'message-square', title: 'Automated DMs', desc: 'Questions, booking and sales without living on your phone.' },
        { icon: 'message-square', title: 'Comment replies', desc: 'Detect buying intent and open a private thread automatically.' },
        { icon: 'smartphone', title: 'Stories & mentions', desc: 'Turn reactions into follow-up conversations.' },
        { icon: 'shopping-bag', title: 'Sell in chat', desc: 'Catalogs, qualification and close in the DM.' },
        { icon: 'bar-chart', title: 'Analytics', desc: 'See what converts and what copy works.' },
        { icon: 'users', title: 'Shared workspace', desc: 'Instagram alongside SMS and other channels.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Connect Instagram',
      stepsTitleAccent: 'in minutes.',
      steps: [
        { n: '01', title: 'Link your account', desc: 'Official messaging permissions.' },
        { n: '02', title: 'Set your rules', desc: 'Pricing, services and escalation.' },
        { n: '03', title: 'AI responds', desc: 'DMs and comments handled instantly.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'For brands',
      useCasesTitleAccent: 'built on Instagram.',
      useCases: [
        { icon: 'scissors', title: 'Beauty & wellness', desc: 'Book from the DM on your latest post.' },
        { icon: 'shopping-bag', title: 'Retail', desc: 'Product and inventory questions answered instantly.' },
        { icon: 'heart', title: 'Services', desc: 'Turn followers into confirmed appointments.' },
        { icon: 'trending-up', title: 'Agencies', desc: 'One platform for every client account.' },
      ],
      trustEyebrow: 'Official integration',
      trustTitle: 'Meta',
      trustTitleAccent: 'Instagram Messaging API.',
      trustLead: 'Secure connection with granular permissions. Your account stays protected and auditable.',
      trustBullets: [
        'Official messaging permissions',
        'Unified history across channels',
        'Human handoff with full context',
        'Meta policy compliant',
      ],
      trustItems: [
        { label: 'Instagram Messaging API', badge: 'Official' },
        { label: 'Unified platform', badge: 'Included' },
        { label: 'Human handoff', badge: '1-click' },
        { label: 'Availability', badge: '24/7' },
      ],
      ctaTitle: 'Your Instagram DMs,',
      ctaAccent: 'always answered.',
      ctaLead: 'Connect Instagram and let Shadia turn every message into a booking or sale.',
      ctaSource: 'channel_instagram_cta',
      ctaHint: 'No credit card · Minutes to set up',
    },
    facebook: {
      lang: 'en',
      title: 'Shadia AI for Messenger — Automated Facebook Messenger',
      description: 'Handle Messenger with AI. Unify with WhatsApp, Instagram and SMS in one operation.',
      canonical: 'https://shadia.ai/en/channels/facebook',
      ogImage: '/og/facebook-en.png',
      badge: 'Messenger · Facebook',
      heroTitle: 'Messenger handled',
      heroAccent: 'without dropped threads.',
      heroLead: 'Shadia replies on Messenger, qualifies inquiries and can continue on SMS or WhatsApp when that\'s better for the customer.',
      source: 'channel_facebook_hero',
      heroHint: 'Meta Business · Unified platform',
      channelId: 'facebook',
      stats: [
        { v: '1.3B+', l: 'Messenger users' },
        { v: '< 90s', l: 'Average response' },
        { v: '24/7', l: 'AI coverage' },
        { v: 'Multi', l: 'Channel handoff' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'Messenger wired',
      featuresTitleAccent: 'into your stack.',
      features: [
        { icon: 'message-square', title: 'Instant replies', desc: 'No page message left unanswered.' },
        { icon: 'bot', title: 'Shared AI context', desc: 'Same business knowledge as your other channels.' },
        { icon: 'repeat', title: 'Continue on SMS', desc: 'Move the thread to the customer\'s preferred channel.' },
        { icon: 'users', title: 'Team workspace', desc: 'Messenger with everything else in one view.' },
        { icon: 'tag', title: 'Tags & notes', desc: 'Shared context on every conversation.' },
        { icon: 'bar-chart', title: 'Reporting', desc: 'Volume, speed and conversion by channel.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Connect your',
      stepsTitleAccent: 'Facebook Page.',
      steps: [
        { n: '01', title: 'Link the page', desc: 'Authorize Messenger from Meta Business.' },
        { n: '02', title: 'Set rules', desc: 'Hours, pricing and when to escalate.' },
        { n: '03', title: 'Go live', desc: 'AI replies while your team oversees.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'For businesses',
      useCasesTitleAccent: 'active on Facebook.',
      useCases: [
        { icon: 'store', title: 'Local business', desc: 'Hours, pricing and location questions.' },
        { icon: 'heart', title: 'Services', desc: 'Book appointments from your Page.' },
        { icon: 'trending-up', title: 'Sales', desc: 'Automatic follow-up on prospects.' },
      ],
      trustEyebrow: 'Meta',
      trustTitle: 'Messenger',
      trustTitleAccent: 'Business API.',
      trustLead: 'Official integration with your Facebook Page and messaging permissions.',
      trustBullets: [
        'Verified business page',
        'Messages within Meta policies',
        'History in unified platform',
        'Human escalation with context',
      ],
      trustItems: [
        { label: 'Messenger API', badge: 'Official' },
        { label: 'Meta Business Suite', badge: 'Compatible' },
        { label: 'SMS handoff', badge: 'Optional' },
        { label: 'Uptime', badge: '99.9%' },
      ],
      ctaTitle: 'Your Facebook Page,',
      ctaAccent: 'always responding.',
      ctaLead: 'Connect Messenger and unify support with your other channels.',
      ctaSource: 'channel_facebook_cta',
      ctaHint: 'No credit card · Meta Business',
    },
    tiktok: {
      lang: 'en',
      title: 'Shadia AI for TikTok — DMs that convert',
      description: 'Reply to TikTok DMs with AI. Turn interest into booked appointments and sales.',
      canonical: 'https://shadia.ai/en/channels/tiktok',
      ogImage: '/og/tiktok-en.png',
      badge: 'TikTok · Direct messages',
      heroTitle: 'TikTok DMs',
      heroAccent: 'that become bookings.',
      heroLead: 'Shadia answers TikTok messages instantly and moves the conversation to a real appointment or sale — with full context in your workspace.',
      source: 'channel_tiktok_hero',
      heroHint: 'Unified platform · No credit card',
      channelId: 'tiktok',
      stats: [
        { v: '1B+', l: 'Active TikTok users' },
        { v: '< 2 min', l: 'First reply' },
        { v: '24/7', l: 'After-hours DMs' },
        { v: '1 place', l: 'All channels together' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'TikTok in your',
      featuresTitleAccent: 'unified operation.',
      features: [
        { icon: 'message-square', title: 'AI DMs', desc: 'Answer questions and suggest next steps immediately.' },
        { icon: 'zap', title: 'Speed', desc: 'Capture video-driven interest before it cools off.' },
        { icon: 'calendar', title: 'Booking', desc: 'Schedule from the DM like any other channel.' },
        { icon: 'users', title: 'Team workspace', desc: 'TikTok with SMS and more in one view.' },
        { icon: 'bot', title: 'Same agent', desc: 'Consistent tone and rules everywhere.' },
        { icon: 'bar-chart', title: 'Metrics', desc: 'See which DMs become customers.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Connect TikTok',
      stepsTitleAccent: 'in a few steps.',
      steps: [
        { n: '01', title: 'Authorize account', desc: 'Secure messaging connection.' },
        { n: '02', title: 'Configure', desc: 'Services, pricing and escalation.' },
        { n: '03', title: 'Go live', desc: 'AI replies from the first DM.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'For brands',
      useCasesTitleAccent: 'growing on TikTok.',
      useCases: [
        { icon: 'scissors', title: 'Beauty', desc: 'From viral video to confirmed appointment.' },
        { icon: 'shopping-bag', title: 'E-commerce', desc: 'Stock and shipping questions answered fast.' },
        { icon: 'graduation-cap', title: 'Courses', desc: 'Enrollment from DMs.' },
        { icon: 'trending-up', title: 'Creators', desc: 'Handle volume without losing leads.' },
      ],
      trustEyebrow: 'Platform',
      trustTitle: 'TikTok',
      trustTitleAccent: 'inside Shadia.',
      trustLead: 'Direct messages in the same platform as WhatsApp, Instagram and Messenger.',
      trustBullets: [
        'DMs in unified platform',
        'Shared context per contact',
        'AI with your business rules',
        'Team escalation',
      ],
      trustItems: [
        { label: 'TikTok Messaging', badge: 'Connected' },
        { label: 'Unified platform', badge: 'Included' },
        { label: 'AI 24/7', badge: 'Active' },
        { label: 'Handoff', badge: 'Human' },
      ],
      ctaTitle: 'Your TikTok DMs,',
      ctaAccent: 'turned into customers.',
      ctaLead: 'Connect TikTok and keep momentum from every video.',
      ctaSource: 'channel_tiktok_cta',
      ctaHint: 'No credit card · Fast setup',
    },
  },
};

export function getChannelPage(lang: Lang, channelId: ChannelId): ChannelPageData {
  return pages[lang][channelId];
}
