import type { Lang } from '../i18n/utils';
import type {
  ChannelFeature,
  ChannelStep,
  ChannelUseCase,
  ChannelTrustItem,
} from '../components/ChannelPageLayout.astro';

export type ChannelId = 'whatsapp' | 'instagram' | 'facebook' | 'tiktok';

export interface ChannelPageData {
  lang: Lang;
  title: string;
  description: string;
  canonical: string;
  ogImage: string;
  badge: string;
  heroTitle: string;
  heroAccent: string;
  heroLead: string;
  source: string;
  heroHint: string;
  channelId: ChannelId;
  stats: { v: string; l: string }[];
  featuresEyebrow: string;
  featuresTitle: string;
  featuresTitleAccent: string;
  features: ChannelFeature[];
  stepsEyebrow: string;
  stepsTitle: string;
  stepsTitleAccent: string;
  steps: ChannelStep[];
  useCasesEyebrow: string;
  useCasesTitle: string;
  useCasesTitleAccent: string;
  useCases: ChannelUseCase[];
  trustEyebrow: string;
  trustTitle: string;
  trustTitleAccent: string;
  trustLead: string;
  trustBullets: string[];
  trustItems: ChannelTrustItem[];
  ctaTitle: string;
  ctaAccent: string;
  ctaLead: string;
  ctaSource: string;
  ctaHint: string;
}

const pages: Record<Lang, Record<ChannelId, ChannelPageData>> = {
  es: {
    whatsapp: {
      lang: 'es',
      title: 'Shadia AI para WhatsApp. Citas, recordatorios y seguimiento clínico',
      description: 'Canal principal para clínicas: agenda citas, envía recordatorios, comparte resúmenes post-consulta y da seguimiento al paciente por WhatsApp.',
      canonical: 'https://shadia.ai/es/canales/whatsapp',
      ogImage: '/og/whatsapp-es.png',
      badge: 'WhatsApp · Canal principal clínico',
      heroTitle: 'Tu clínica',
      heroAccent: 'donde ya están tus pacientes.',
      heroLead: 'WhatsApp es donde tus pacientes ya te escriben. Shadia agenda citas, confirma visitas, envía preparación pre-consulta y comparte resúmenes, tu equipo interviene solo cuando importa.',
      source: 'channel_whatsapp_hero',
      heroHint: 'API oficial de WhatsApp · Sin tarjeta de crédito',
      channelId: 'whatsapp',
      stats: [
        { v: '98%', l: 'Tasa de apertura de recordatorios' },
        { v: '40%', l: 'Reducción promedio de no-shows' },
        { v: '< 30 s', l: 'Primera respuesta de recepción IA' },
        { v: '24/7', l: 'Recepción disponible' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'Todo lo clínico,',
      featuresTitleAccent: 'directamente en WhatsApp.',
      features: [
        { icon: 'calendar', title: 'Citas por WhatsApp', desc: 'El paciente pide cita en el chat. La recepcionista IA confirma, reagenda y sincroniza con el calendario.' },
        { icon: 'bell', title: 'Recordatorios automáticos', desc: 'Confirmación 24h y 1h antes. Preparación pre-visita y alertas de no-show sin llamadas manuales.' },
        { icon: 'clipboard', title: 'Resúmenes post-consulta', desc: 'Instrucciones de cuidado, medicación y próximo control enviados al paciente después de la visita.' },
        { icon: 'bot', title: 'Recepcionista IA 24/7', desc: 'Horarios, ubicación, servicios, seguro y requisitos de la visita, respondidos al instante.' },
        { icon: 'user-check', title: 'Escalación con contexto', desc: 'Casos sensibles o fuera de protocolo pasan al equipo con historial completo del paciente.' },
        { icon: 'megaphone', title: 'Seguimiento segmentado', desc: 'Recordatorios de control, campañas de prevención y reactivación de pacientes inactivos.' },
        { icon: 'tag', title: 'Expediente del paciente', desc: 'Cada conversación queda vinculada al perfil clínico con historial completo.' },
        { icon: 'link', title: 'API oficial', desc: 'WhatsApp Business API con número verificado, plantillas aprobadas y máxima entregabilidad.' },
        { icon: 'bar-chart', title: 'Métricas clínicas', desc: 'Citas agendadas, no-shows, tiempos de respuesta y satisfacción del paciente.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'De cero a operando',
      stepsTitleAccent: 'en menos de una hora.',
      steps: [
        { n: '01', title: 'Conecta tu número', desc: 'Vincula WhatsApp Business de la clínica en minutos.' },
        { n: '02', title: 'Configura tu clínica', desc: 'Servicios, horarios, médicos y reglas de escalación, sin código.' },
        { n: '03', title: 'Shadia empieza', desc: 'Agenda, confirma y da seguimiento desde el primer mensaje.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Ideal para',
      useCasesTitleAccent: 'clínicas y consultorios.',
      useCases: [
        { icon: 'heart', title: 'Clínicas generales', desc: 'Citas, recordatorios y FAQs de consulta por WhatsApp.' },
        { icon: 'scissors', title: 'Odontología', desc: 'Agenda procedimientos, envía preparación y confirma asistencia.' },
        { icon: 'heart', title: 'Salud mental', desc: 'Agenda sesiones con tono empático y recordatorios discretos.' },
        { icon: 'clipboard', title: 'Redes multi-sede', desc: 'Un número o varios, con routing por sede y especialidad.' },
      ],
      trustEyebrow: 'API Oficial',
      trustTitle: 'Conectado a la',
      trustTitleAccent: 'WhatsApp Business API oficial.',
      trustLead: 'Shadia opera sobre la API oficial de Meta. Número verificado, plantillas aprobadas y entregabilidad máxima para recordatorios clínicos.',
      trustBullets: [
        'Número verificado con sello verde',
        'Plantillas aprobadas para recordatorios',
        'Botones interactivos para confirmar citas',
        'Cifrado de extremo a extremo',
      ],
      trustItems: [
        { label: 'Meta Business Partner', badge: 'Verificado' },
        { label: 'WhatsApp Business API', badge: 'Oficial' },
        { label: 'Datos cifrados', badge: 'Seguro' },
        { label: 'Uptime garantizado', badge: '99.9%' },
      ],
      ctaTitle: 'Tu clínica en WhatsApp,',
      ctaAccent: 'sin pacientes esperando.',
      ctaLead: 'Conecta tu número hoy y Shadia empieza a gestionar citas y seguimiento desde el primer minuto.',
      ctaSource: 'channel_whatsapp_cta',
      ctaHint: 'Sin tarjeta de crédito · API oficial · Listo en menos de 1 hora',
    },
    instagram: {
      lang: 'es',
      title: 'Shadia AI para Instagram. Consultas de estética y citas desde DMs',
      description: 'Ideal para clínicas de estética: responde consultas de procedimientos, califica pacientes y agenda citas desde Instagram DMs y comentarios.',
      canonical: 'https://shadia.ai/es/canales/instagram',
      ogImage: '/og/instagram-es.png',
      badge: 'Instagram · Estética y consultas',
      heroTitle: 'Cada DM de estética,',
      heroAccent: 'convertido en cita.',
      heroLead: 'Tus pacientes preguntan por procedimientos en Instagram. Shadia responde al instante, califica la consulta y agenda la evaluación, 24/7, con el mismo expediente que WhatsApp.',
      source: 'channel_instagram_hero',
      heroHint: 'Unificado con WhatsApp · Sin tarjeta de crédito',
      channelId: 'instagram',
      stats: [
        { v: '< 2 min', l: 'Primera respuesta a consultas' },
        { v: '24/7', l: 'DMs atendidos fuera de horario' },
        { v: '1 perfil', l: 'Paciente unificado con WhatsApp' },
        { v: '3x', l: 'Más citas desde contenido social' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'Instagram para',
      featuresTitleAccent: 'clínicas de estética.',
      features: [
        { icon: 'message-square', title: 'DMs de procedimientos', desc: 'Responde preguntas sobre botox, rellenos, láser y más, con información de tu clínica.' },
        { icon: 'message-square', title: 'Comentarios con intención', desc: 'Detecta "¿precio?", "¿cita?" o "info" en comentarios y abre conversación privada.' },
        { icon: 'calendar', title: 'Agenda desde el DM', desc: 'Califica la consulta y ofrece horarios disponibles sin salir de Instagram.' },
        { icon: 'smartphone', title: 'Stories y reels', desc: 'Convierte reacciones a contenido de estética en consultas y evaluaciones agendadas.' },
        { icon: 'repeat', title: 'Continuar en WhatsApp', desc: 'Mueve la conversación a WhatsApp para confirmación, recordatorios y seguimiento post-procedimiento.' },
        { icon: 'users', title: 'Equipo unificado', desc: 'Instagram junto con WhatsApp y otros canales en un solo expediente del paciente.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'Conecta Instagram',
      stepsTitleAccent: 'y empieza en minutos.',
      steps: [
        { n: '01', title: 'Vincula tu cuenta', desc: 'Conexión oficial con permisos de mensajes de la clínica.' },
        { n: '02', title: 'Define procedimientos', desc: 'Servicios, precios orientativos, contraindicaciones y reglas de escalación.' },
        { n: '03', title: 'La IA responde', desc: 'DMs y comentarios gestionados al instante, citas agendadas.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Ideal para',
      useCasesTitleAccent: 'estética y bienestar.',
      useCases: [
        { icon: 'scissors', title: 'Medicina estética', desc: 'Consultas de botox, rellenos y tratamientos faciales desde el DM.' },
        { icon: 'heart', title: 'Dermatología estética', desc: 'Agenda evaluaciones desde posts de antes/después.' },
        { icon: 'scissors', title: 'Cirugía plástica', desc: 'Califica consultas y agenda evaluaciones pre-quirúrgicas.' },
        { icon: 'heart', title: 'Spa clínico', desc: 'Convierte seguidores en citas de tratamientos.' },
      ],
      trustEyebrow: 'Integración oficial',
      trustTitle: 'API de Meta',
      trustTitleAccent: 'para Instagram Messaging.',
      trustLead: 'Conexión segura con permisos granulares. Tu cuenta protegida y auditable, con historial unificado en el expediente del paciente.',
      trustBullets: [
        'Permisos oficiales de mensajería',
        'Expediente unificado con WhatsApp',
        'Escalación al equipo con contexto clínico',
        'Cumplimiento de políticas de Meta',
      ],
      trustItems: [
        { label: 'Instagram Messaging API', badge: 'Oficial' },
        { label: 'Expediente unificado', badge: 'Incluido' },
        { label: 'Handoff humano', badge: '1 clic' },
        { label: 'Disponibilidad', badge: '24/7' },
      ],
      ctaTitle: 'Tus DMs de estética,',
      ctaAccent: 'convertidos en citas.',
      ctaLead: 'Conecta Instagram y deja que Shadia convierta cada consulta en una evaluación agendada.',
      ctaSource: 'channel_instagram_cta',
      ctaHint: 'Sin tarjeta de crédito · Setup en minutos',
    },
    facebook: {
      lang: 'es',
      title: 'Shadia AI para Messenger. Página de clínica atendida 24/7',
      description: 'Atiende la página de Facebook de tu clínica con IA. Consultas, citas y handoff a WhatsApp para seguimiento clínico.',
      canonical: 'https://shadia.ai/es/canales/facebook',
      ogImage: '/og/facebook-es.png',
      badge: 'Messenger · Página de clínica',
      heroTitle: 'Tu página de clínica,',
      heroAccent: 'siempre respondiendo.',
      heroLead: 'Pacientes escriben a tu página de Facebook con dudas sobre servicios, horarios y citas. Shadia responde al instante y puede continuar en WhatsApp para recordatorios y seguimiento.',
      source: 'channel_facebook_hero',
      heroHint: 'Meta Business · Unificado con WhatsApp',
      channelId: 'facebook',
      stats: [
        { v: '1.3B+', l: 'Usuarios de Messenger' },
        { v: '< 90s', l: 'Respuesta promedio' },
        { v: '24/7', l: 'Cobertura con recepcionista IA' },
        { v: 'WhatsApp', l: 'Handoff para seguimiento clínico' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'Messenger conectado',
      featuresTitleAccent: 'a tu operación clínica.',
      features: [
        { icon: 'message-square', title: 'Respuestas instantáneas', desc: 'Horarios, ubicación, servicios y requisitos de la visita, sin dejar mensajes sin respuesta.' },
        { icon: 'calendar', title: 'Citas desde Messenger', desc: 'Agenda consultas directamente desde la página de la clínica.' },
        { icon: 'repeat', title: 'Continuar en WhatsApp', desc: 'Ofrece seguir por WhatsApp para confirmación, recordatorios y seguimiento post-consulta.' },
        { icon: 'bot', title: 'Mismo contexto clínico', desc: 'La recepcionista IA conoce tus servicios, médicos y reglas, igual que en WhatsApp.' },
        { icon: 'users', title: 'Equipo unificado', desc: 'Messenger junto con WhatsApp e Instagram en un solo lugar.' },
        { icon: 'bar-chart', title: 'Reportes', desc: 'Volumen, conversiones a cita y tiempos de respuesta por canal.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'Conecta tu página',
      stepsTitleAccent: 'de clínica.',
      steps: [
        { n: '01', title: 'Vincula la página', desc: 'Autoriza Messenger desde Meta Business de la clínica.' },
        { n: '02', title: 'Configura servicios', desc: 'Horarios, especialidades, médicos y cuándo escalar.' },
        { n: '03', title: 'Operación activa', desc: 'La recepcionista IA responde y tu equipo supervisa.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Para clínicas con',
      useCasesTitleAccent: 'presencia en Facebook.',
      useCases: [
        { icon: 'heart', title: 'Clínicas locales', desc: 'Consultas de horario, ubicación y servicios disponibles.' },
        { icon: 'heart', title: 'Centros de salud', desc: 'Agenda citas desde la página institucional.' },
        { icon: 'scissors', title: 'Estética', desc: 'Consultas de procedimientos con handoff a WhatsApp.' },
      ],
      trustEyebrow: 'Meta',
      trustTitle: 'Messenger',
      trustTitleAccent: 'Business API.',
      trustLead: 'Integración oficial con la página de Facebook de tu clínica y permisos de mensajería.',
      trustBullets: [
        'Página verificada de la clínica',
        'Mensajes dentro de políticas de Meta',
        'Expediente unificado con WhatsApp',
        'Escalación al equipo con contexto',
      ],
      trustItems: [
        { label: 'Messenger API', badge: 'Oficial' },
        { label: 'Meta Business Suite', badge: 'Compatible' },
        { label: 'Handoff WhatsApp', badge: 'Incluido' },
        { label: 'Uptime', badge: '99.9%' },
      ],
      ctaTitle: 'Tu página de clínica,',
      ctaAccent: 'siempre atendida.',
      ctaLead: 'Conecta Messenger y unifica la atención con WhatsApp e Instagram.',
      ctaSource: 'channel_facebook_cta',
      ctaHint: 'Sin tarjeta de crédito · Meta Business',
    },
    tiktok: {
      lang: 'es',
      title: 'Shadia AI para TikTok. Marketing de estética que convierte en citas',
      description: 'Convierte DMs de TikTok en consultas y citas para clínicas de estética. Captura el interés de tus videos antes de que se enfríe.',
      canonical: 'https://shadia.ai/es/canales/tiktok',
      ogImage: '/og/tiktok-es.png',
      badge: 'TikTok · Marketing estético',
      heroTitle: 'DMs de TikTok',
      heroAccent: 'que llegan a evaluación.',
      heroLead: 'Tus videos de estética generan interés. Shadia atiende los DMs al instante, responde consultas de procedimientos y agenda evaluaciones, con el mismo expediente que WhatsApp.',
      source: 'channel_tiktok_hero',
      heroHint: 'Unificado con WhatsApp · Sin tarjeta',
      channelId: 'tiktok',
      stats: [
        { v: '1B+', l: 'Usuarios activos en TikTok' },
        { v: '< 2 min', l: 'Primera respuesta a DMs' },
        { v: '24/7', l: 'DMs fuera de horario' },
        { v: '3x', l: 'Más citas desde contenido viral' },
      ],
      featuresEyebrow: 'Funcionalidades',
      featuresTitle: 'TikTok para',
      featuresTitleAccent: 'marketing clínico.',
      features: [
        { icon: 'message-square', title: 'DMs con recepcionista IA', desc: 'Responde "¿precio?", "¿duele?" y "¿cita?" al instante con info de tu clínica.' },
        { icon: 'zap', title: 'Captura el momentum', desc: 'Responde mientras el interés del video está caliente, no al día siguiente.' },
        { icon: 'calendar', title: 'Agenda evaluaciones', desc: 'Ofrece horarios y confirma citas desde el DM, con seguimiento por WhatsApp.' },
        { icon: 'repeat', title: 'Handoff a WhatsApp', desc: 'Mueve la conversación a WhatsApp para recordatorios y seguimiento post-procedimiento.' },
        { icon: 'bot', title: 'Mismo agente clínico', desc: 'Tono, servicios y reglas consistentes con WhatsApp e Instagram.' },
        { icon: 'bar-chart', title: 'Métricas', desc: 'Qué videos y DMs generan más evaluaciones agendadas.' },
      ],
      stepsEyebrow: 'Cómo funciona',
      stepsTitle: 'Conecta TikTok',
      stepsTitleAccent: 'en pocos pasos.',
      steps: [
        { n: '01', title: 'Autoriza la cuenta', desc: 'Conexión segura para mensajes de la clínica.' },
        { n: '02', title: 'Configura procedimientos', desc: 'Servicios de estética, precios orientativos y escalación.' },
        { n: '03', title: 'Empieza', desc: 'La recepcionista IA responde desde el primer DM.' },
      ],
      useCasesEyebrow: 'Casos de uso',
      useCasesTitle: 'Para clínicas de estética',
      useCasesTitleAccent: 'que crecen en TikTok.',
      useCases: [
        { icon: 'scissors', title: 'Medicina estética', desc: 'Del video de botox a la evaluación confirmada.' },
        { icon: 'heart', title: 'Dermatología', desc: 'Consultas de tratamientos desde contenido educativo.' },
        { icon: 'scissors', title: 'Cirugía estética', desc: 'Califica interés y agenda evaluaciones pre-quirúrgicas.' },
        { icon: 'heart', title: 'Bienestar', desc: 'Convierte seguidores en pacientes de primera consulta.' },
      ],
      trustEyebrow: 'Plataforma',
      trustTitle: 'TikTok',
      trustTitleAccent: 'integrado con Shadia.',
      trustLead: 'DMs en la misma plataforma que WhatsApp e Instagram, un expediente del paciente, una operación clínica.',
      trustBullets: [
        'DMs en plataforma unificada',
        'Expediente compartido por paciente',
        'Recepcionista IA con reglas de tu clínica',
        'Escalación al equipo clínico',
      ],
      trustItems: [
        { label: 'TikTok Messaging', badge: 'Conectado' },
        { label: 'Expediente unificado', badge: 'Incluido' },
        { label: 'Recepcionista IA', badge: '24/7' },
        { label: 'Handoff WhatsApp', badge: 'Incluido' },
      ],
      ctaTitle: 'Tus DMs de TikTok,',
      ctaAccent: 'convertidos en pacientes.',
      ctaLead: 'Conecta TikTok y no pierdas el interés que generan tus videos de estética.',
      ctaSource: 'channel_tiktok_cta',
      ctaHint: 'Sin tarjeta de crédito · Setup rápido',
    },
  },
  en: {
    whatsapp: {
      lang: 'en',
      title: 'Shadia AI for WhatsApp. Appointments, reminders & clinical follow-up',
      description: 'Primary channel for clinics: book appointments, send reminders, share post-visit summaries, and follow up with patients on WhatsApp.',
      canonical: 'https://shadia.ai/en/channels/whatsapp',
      ogImage: '/og/whatsapp-en.png',
      badge: 'WhatsApp · Primary clinical channel',
      heroTitle: 'Your practice,',
      heroAccent: 'where patients already are.',
      heroLead: 'WhatsApp is the primary channel for patient communication. Shadia books appointments, confirms visits, sends pre-visit prep, and shares summaries, your team steps in only when it matters.',
      source: 'channel_whatsapp_hero',
      heroHint: 'Official WhatsApp API · No credit card',
      channelId: 'whatsapp',
      stats: [
        { v: '98%', l: 'Reminder open rate' },
        { v: '40%', l: 'Average no-show reduction' },
        { v: '< 30 s', l: 'AI receptionist first response' },
        { v: '24/7', l: 'Front desk available' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'Everything clinical,',
      featuresTitleAccent: 'right in WhatsApp.',
      features: [
        { icon: 'calendar', title: 'WhatsApp booking', desc: 'Patient requests an appointment in chat. AI receptionist confirms, reschedules, and syncs with your calendar.' },
        { icon: 'bell', title: 'Automatic reminders', desc: '24h and 1h confirmation. Pre-visit prep and no-show alerts without manual calls.' },
        { icon: 'clipboard', title: 'Post-visit summaries', desc: 'Care instructions, medication guidance, and follow-up reminders sent after the visit.' },
        { icon: 'bot', title: '24/7 AI receptionist', desc: 'Hours, location, services, insurance, and visit requirements, answered instantly.' },
        { icon: 'user-check', title: 'Escalation with context', desc: 'Sensitive or out-of-protocol cases go to staff with full patient history.' },
        { icon: 'megaphone', title: 'Segmented follow-up', desc: 'Follow-up reminders, preventive care campaigns, and inactive patient reactivation.' },
        { icon: 'tag', title: 'Patient record', desc: 'Every conversation links to the clinical profile with full history.' },
        { icon: 'link', title: 'Official API', desc: 'WhatsApp Business API with verified number, approved templates, and maximum deliverability.' },
        { icon: 'bar-chart', title: 'Clinical metrics', desc: 'Appointments booked, no-shows, response times, and patient satisfaction.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Live in under',
      stepsTitleAccent: 'an hour.',
      steps: [
        { n: '01', title: 'Connect your number', desc: 'Link your practice WhatsApp Business in minutes.' },
        { n: '02', title: 'Configure your practice', desc: 'Services, hours, providers, and escalation rules, no code.' },
        { n: '03', title: 'Shadia goes live', desc: 'Books, confirms, and follows up from message one.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'Built for',
      useCasesTitleAccent: 'clinics and practices.',
      useCases: [
        { icon: 'heart', title: 'Primary care', desc: 'Appointments, reminders, and visit FAQs on WhatsApp.' },
        { icon: 'scissors', title: 'Dental', desc: 'Schedule procedures, send prep instructions, and confirm attendance.' },
        { icon: 'heart', title: 'Mental health', desc: 'Book sessions with empathetic tone and discreet reminders.' },
        { icon: 'clipboard', title: 'Multi-site networks', desc: 'One number or many, with routing by location and specialty.' },
      ],
      trustEyebrow: 'Official API',
      trustTitle: 'Connected to',
      trustTitleAccent: 'WhatsApp Business API.',
      trustLead: 'Shadia runs on Meta\'s official API, verified number, approved templates, and maximum deliverability for clinical reminders.',
      trustBullets: [
        'Verified business number',
        'Approved reminder templates',
        'Interactive buttons to confirm appointments',
        'End-to-end encryption',
      ],
      trustItems: [
        { label: 'Meta Business Partner', badge: 'Verified' },
        { label: 'WhatsApp Business API', badge: 'Official' },
        { label: 'Encrypted data', badge: 'Secure' },
        { label: 'Guaranteed uptime', badge: '99.9%' },
      ],
      ctaTitle: 'Your practice on WhatsApp,',
      ctaAccent: 'without patients waiting.',
      ctaLead: 'Connect your number today and Shadia starts managing appointments and follow-up immediately.',
      ctaSource: 'channel_whatsapp_cta',
      ctaHint: 'No credit card · Official API · Under 1 hour setup',
    },
    instagram: {
      lang: 'en',
      title: 'Shadia AI for Instagram. Aesthetics inquiries & booking from DMs',
      description: 'Ideal for aesthetics practices: answer procedure questions, qualify patients, and book consultations from Instagram DMs and comments.',
      canonical: 'https://shadia.ai/en/channels/instagram',
      ogImage: '/og/instagram-en.png',
      badge: 'Instagram · Aesthetics & inquiries',
      heroTitle: 'Every aesthetics DM,',
      heroAccent: 'turned into a booking.',
      heroLead: 'Patients ask about procedures on Instagram. Shadia replies instantly, qualifies the inquiry, and books the consultation, 24/7, with the same record as WhatsApp.',
      source: 'channel_instagram_hero',
      heroHint: 'Unified with WhatsApp · No credit card',
      channelId: 'instagram',
      stats: [
        { v: '< 2 min', l: 'First reply to inquiries' },
        { v: '24/7', l: 'After-hours DM coverage' },
        { v: '1 record', l: 'Patient unified with WhatsApp' },
        { v: '3x', l: 'More bookings from social content' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'Instagram for',
      featuresTitleAccent: 'aesthetics practices.',
      features: [
        { icon: 'message-square', title: 'Procedure DMs', desc: 'Answer questions about Botox, fillers, laser, and more, with your practice information.' },
        { icon: 'message-square', title: 'Intent comments', desc: 'Detect "price?", "booking?" or "info" in comments and open a private thread.' },
        { icon: 'calendar', title: 'Book from the DM', desc: 'Qualify the inquiry and offer available times without leaving Instagram.' },
        { icon: 'smartphone', title: 'Stories & reels', desc: 'Turn reactions to aesthetics content into booked consultations.' },
        { icon: 'repeat', title: 'Continue on WhatsApp', desc: 'Move the conversation to WhatsApp for confirmation, reminders, and post-procedure follow-up.' },
        { icon: 'users', title: 'Unified team workspace', desc: 'Instagram alongside WhatsApp and other channels in one patient record.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Connect Instagram',
      stepsTitleAccent: 'in minutes.',
      steps: [
        { n: '01', title: 'Link your account', desc: 'Official connection with your practice messaging permissions.' },
        { n: '02', title: 'Define procedures', desc: 'Services, pricing guidance, contraindications, and escalation rules.' },
        { n: '03', title: 'AI responds', desc: 'DMs and comments handled instantly, appointments booked.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'Built for',
      useCasesTitleAccent: 'aesthetics & wellness.',
      useCases: [
        { icon: 'scissors', title: 'Medical aesthetics', desc: 'Botox, filler, and facial treatment inquiries from the DM.' },
        { icon: 'heart', title: 'Cosmetic dermatology', desc: 'Book evaluations from before/after posts.' },
        { icon: 'scissors', title: 'Plastic surgery', desc: 'Qualify inquiries and schedule pre-surgical consultations.' },
        { icon: 'heart', title: 'Medical spa', desc: 'Turn followers into treatment appointments.' },
      ],
      trustEyebrow: 'Official integration',
      trustTitle: 'Meta',
      trustTitleAccent: 'Instagram Messaging API.',
      trustLead: 'Secure connection with granular permissions. Your account stays protected and auditable, with unified history in the patient record.',
      trustBullets: [
        'Official messaging permissions',
        'Unified record with WhatsApp',
        'Human handoff with clinical context',
        'Meta policy compliant',
      ],
      trustItems: [
        { label: 'Instagram Messaging API', badge: 'Official' },
        { label: 'Unified record', badge: 'Included' },
        { label: 'Human handoff', badge: '1-click' },
        { label: 'Availability', badge: '24/7' },
      ],
      ctaTitle: 'Your aesthetics DMs,',
      ctaAccent: 'turned into bookings.',
      ctaLead: 'Connect Instagram and let Shadia turn every inquiry into a scheduled consultation.',
      ctaSource: 'channel_instagram_cta',
      ctaHint: 'No credit card · Minutes to set up',
    },
    facebook: {
      lang: 'en',
      title: 'Shadia AI for Messenger. Your clinic page, answered 24/7',
      description: 'Handle your clinic\'s Facebook page with AI. Inquiries, appointments, and handoff to WhatsApp for clinical follow-up.',
      canonical: 'https://shadia.ai/en/channels/facebook',
      ogImage: '/og/facebook-en.png',
      badge: 'Messenger · Clinic page',
      heroTitle: 'Your clinic page,',
      heroAccent: 'always responding.',
      heroLead: 'Patients message your Facebook page with questions about services, hours, and appointments. Shadia replies instantly and can continue on WhatsApp for reminders and follow-up.',
      source: 'channel_facebook_hero',
      heroHint: 'Meta Business · Unified with WhatsApp',
      channelId: 'facebook',
      stats: [
        { v: '1.3B+', l: 'Messenger users' },
        { v: '< 90s', l: 'Average response' },
        { v: '24/7', l: 'AI receptionist coverage' },
        { v: 'WhatsApp', l: 'Handoff for clinical follow-up' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'Messenger wired',
      featuresTitleAccent: 'into your clinical operation.',
      features: [
        { icon: 'message-square', title: 'Instant replies', desc: 'Hours, location, services, and visit requirements, no unanswered page messages.' },
        { icon: 'calendar', title: 'Book from Messenger', desc: 'Schedule appointments directly from your clinic page.' },
        { icon: 'repeat', title: 'Continue on WhatsApp', desc: 'Offer to move to WhatsApp for confirmation, reminders, and post-visit follow-up.' },
        { icon: 'bot', title: 'Same clinical context', desc: 'The AI receptionist knows your services, providers, and rules, same as WhatsApp.' },
        { icon: 'users', title: 'Unified workspace', desc: 'Messenger alongside WhatsApp and Instagram in one place.' },
        { icon: 'bar-chart', title: 'Reporting', desc: 'Volume, appointment conversions, and response times by channel.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Connect your',
      stepsTitleAccent: 'clinic page.',
      steps: [
        { n: '01', title: 'Link the page', desc: 'Authorize Messenger from your clinic Meta Business account.' },
        { n: '02', title: 'Configure services', desc: 'Hours, specialties, providers, and when to escalate.' },
        { n: '03', title: 'Go live', desc: 'AI receptionist replies while your team oversees.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'For clinics with',
      useCasesTitleAccent: 'a Facebook presence.',
      useCases: [
        { icon: 'heart', title: 'Local clinics', desc: 'Hours, location, and available services questions.' },
        { icon: 'heart', title: 'Health centers', desc: 'Book appointments from the institutional page.' },
        { icon: 'scissors', title: 'Aesthetics', desc: 'Procedure inquiries with handoff to WhatsApp.' },
      ],
      trustEyebrow: 'Meta',
      trustTitle: 'Messenger',
      trustTitleAccent: 'Business API.',
      trustLead: 'Official integration with your clinic Facebook Page and messaging permissions.',
      trustBullets: [
        'Verified clinic page',
        'Messages within Meta policies',
        'Unified record with WhatsApp',
        'Human escalation with context',
      ],
      trustItems: [
        { label: 'Messenger API', badge: 'Official' },
        { label: 'Meta Business Suite', badge: 'Compatible' },
        { label: 'WhatsApp handoff', badge: 'Included' },
        { label: 'Uptime', badge: '99.9%' },
      ],
      ctaTitle: 'Your clinic page,',
      ctaAccent: 'always covered.',
      ctaLead: 'Connect Messenger and unify patient communication with WhatsApp and Instagram.',
      ctaSource: 'channel_facebook_cta',
      ctaHint: 'No credit card · Meta Business',
    },
    tiktok: {
      lang: 'en',
      title: 'Shadia AI for TikTok. Aesthetics marketing that converts to bookings',
      description: 'Turn TikTok DMs into consultations and appointments for aesthetics practices. Capture interest from your videos before it cools off.',
      canonical: 'https://shadia.ai/en/channels/tiktok',
      ogImage: '/og/tiktok-en.png',
      badge: 'TikTok · Aesthetics marketing',
      heroTitle: 'TikTok DMs',
      heroAccent: 'that become consultations.',
      heroLead: 'Your aesthetics videos drive interest. Shadia answers DMs instantly, responds to procedure questions, and books consultations, with the same record as WhatsApp.',
      source: 'channel_tiktok_hero',
      heroHint: 'Unified with WhatsApp · No credit card',
      channelId: 'tiktok',
      stats: [
        { v: '1B+', l: 'Active TikTok users' },
        { v: '< 2 min', l: 'First DM reply' },
        { v: '24/7', l: 'After-hours DMs' },
        { v: '3x', l: 'More bookings from viral content' },
      ],
      featuresEyebrow: 'Features',
      featuresTitle: 'TikTok for',
      featuresTitleAccent: 'clinical marketing.',
      features: [
        { icon: 'message-square', title: 'AI receptionist DMs', desc: 'Answer "price?", "does it hurt?" and "booking?" instantly with your practice info.' },
        { icon: 'zap', title: 'Capture momentum', desc: 'Reply while video interest is hot, not the next day.' },
        { icon: 'calendar', title: 'Book consultations', desc: 'Offer times and confirm appointments from the DM, with WhatsApp follow-up.' },
        { icon: 'repeat', title: 'Handoff to WhatsApp', desc: 'Move the conversation to WhatsApp for reminders and post-procedure follow-up.' },
        { icon: 'bot', title: 'Same clinical agent', desc: 'Consistent tone, services, and rules with WhatsApp and Instagram.' },
        { icon: 'bar-chart', title: 'Metrics', desc: 'See which videos and DMs drive the most booked consultations.' },
      ],
      stepsEyebrow: 'How it works',
      stepsTitle: 'Connect TikTok',
      stepsTitleAccent: 'in a few steps.',
      steps: [
        { n: '01', title: 'Authorize account', desc: 'Secure messaging connection for your practice.' },
        { n: '02', title: 'Configure procedures', desc: 'Aesthetics services, pricing guidance, and escalation.' },
        { n: '03', title: 'Go live', desc: 'AI receptionist replies from the first DM.' },
      ],
      useCasesEyebrow: 'Use cases',
      useCasesTitle: 'For aesthetics practices',
      useCasesTitleAccent: 'growing on TikTok.',
      useCases: [
        { icon: 'scissors', title: 'Medical aesthetics', desc: 'From Botox video to confirmed consultation.' },
        { icon: 'heart', title: 'Dermatology', desc: 'Treatment inquiries from educational content.' },
        { icon: 'scissors', title: 'Cosmetic surgery', desc: 'Qualify interest and schedule pre-surgical evaluations.' },
        { icon: 'heart', title: 'Wellness', desc: 'Turn followers into first-time patients.' },
      ],
      trustEyebrow: 'Platform',
      trustTitle: 'TikTok',
      trustTitleAccent: 'inside Shadia.',
      trustLead: 'DMs in the same platform as WhatsApp and Instagram, one patient record, one clinical operation.',
      trustBullets: [
        'DMs in unified platform',
        'Shared record per patient',
        'AI receptionist with your practice rules',
        'Escalation to clinical team',
      ],
      trustItems: [
        { label: 'TikTok Messaging', badge: 'Connected' },
        { label: 'Unified record', badge: 'Included' },
        { label: 'AI receptionist', badge: '24/7' },
        { label: 'WhatsApp handoff', badge: 'Included' },
      ],
      ctaTitle: 'Your TikTok DMs,',
      ctaAccent: 'turned into patients.',
      ctaLead: 'Connect TikTok and keep the interest your aesthetics videos generate.',
      ctaSource: 'channel_tiktok_cta',
      ctaHint: 'No credit card · Fast setup',
    },
  },
};

export function getChannelPage(lang: Lang, channelId: ChannelId): ChannelPageData {
  return pages[lang][channelId];
}
